import { useQuery } from '@tanstack/react-query'
import { useEffect, useMemo, useState } from 'react'

import { generateApi } from '../api/generate-post.api'
import { QUERY_KEYS } from '../config/constant'
import { extractedLinksType } from '../models/generate-post.model'
import { IPost } from '../models/post.model'
import { channelType } from '../models/social.model'

export const useGeneratePosts = (
  initialPrompt: string,
  initialSearch?: boolean,
  initialChannel?: channelType | null,
  baseInput?: string | null
) => {
  // ---- State ----
  const [userPrompt, setUserPrompt] = useState(initialPrompt)
  const [userSearch, setUserSearch] = useState<boolean | undefined>(
    initialSearch
  )
  const [userChannel, setUserChannel] = useState<
    channelType | null | undefined
  >(initialChannel)
  const [sessionId, setSessionId] = useState<string | null>(null)

  // ---- Computed Variables ----
  const activePrompt = userPrompt || initialPrompt || ''
  const activeSearch = userSearch ?? initialSearch ?? false
  const activeChannel = userChannel ?? initialChannel ?? null
  const activeBaseInput = baseInput || null
  const key = QUERY_KEYS.generateAIPost

  // ---- Hooks ----
  const query = useQuery({
    // Excluding sessionId to avoid re-fetch when it's set after first response
    // eslint-disable-next-line @tanstack/query/exhaustive-deps
    queryKey: [key, activePrompt, activeSearch, activeChannel],
    queryFn: ({ signal }) =>
      generateApi.generatePost(
        {
          user_prompt: activePrompt,
          is_search_enabled: activeSearch,
          ...(activeChannel ? { post_channels: [activeChannel] } : {}),
          ...(sessionId ? { session_id: sessionId } : {}),
          base_input: activeBaseInput,
        },
        signal
      ),
    enabled: !!activePrompt,
    staleTime: 0,
    gcTime: 0,
    refetchOnMount: false,
  })

  // ---- Effects ----
  /**
   * Sets the session id for further API request calls.
   */
  useEffect(() => {
    if (query.data?.data.session_id) {
      setSessionId(query.data.data.session_id)
    }
  }, [query.data?.data.session_id])

  // ---- Variables ----
  /**
   * Posts generated by the API
   */
  const posts: Pick<IPost, 'id' | 'channel' | 'content'>[] = useMemo(() => {
    const postsResult: Pick<IPost, 'id' | 'channel' | 'content'>[] = []

    if (!query.data?.data) {
      return postsResult
    }

    if (query.data.data.generated_linkedin_post?.content) {
      postsResult.push({
        id: '0',
        channel: 'LinkedIn',
        content: query.data.data.generated_linkedin_post.content,
      })
    }

    if (query.data.data.generated_twitter_post?.content) {
      postsResult.push({
        id: '1',
        channel: 'Twitter',
        content: query.data.data.generated_twitter_post.content,
      })
    }

    return postsResult
  }, [query.data?.data])

  /**
   * Extracted links from the API response
   */
  const extractedLinks: extractedLinksType[] =
    query.data?.data.external_sources ?? []

  return {
    // Query state
    ...query,

    // Data
    posts,
    extractedLinks,

    // Current state
    activePrompt,
    key,
    userChannel,

    // Setters
    setSessionId,
    setUserPrompt,
    setUserSearch,
    setUserChannel,
  }
}
