import { useQuery } from '@tanstack/react-query'
import posthog from 'posthog-js'
import { useEffect, useMemo, useRef, useState } from 'react'
import { toast } from 'sonner'

import { HistoryEntry } from '@/creation/components/PastResponse'
import { SourceChip } from '@/shared/components/sources-card'

import { generateApi } from '../api/generate-post.api'
import { QUERY_KEYS } from '../config/constant'
import { postHogGenerationCapture } from '../config/posthog.config'
import { IPost } from '../models/post.model'
import { channelType } from '../models/social.model'

export const useGeneratePosts = (
  initialPrompt: string,
  initialSearch?: boolean,
  initialChannel?: channelType | null,
  currentState?: {
    linkedin: string | null
    twitter: string | null
  } | null
) => {
  // ---- State ----
  const [userPrompt, setUserPrompt] = useState('')
  const [userSearch, setUserSearch] = useState<boolean | undefined>(undefined)
  const [userChannel, setUserChannel] = useState<channelType | null>(null)
  const [sessionId, setSessionId] = useState<string | null>(null)
  const [history, setHistory] = useState<HistoryEntry[]>([])

  useEffect(() => {
    if (initialChannel) {
      setUserChannel(initialChannel)
    }
    if (initialPrompt) {
      setUserPrompt(initialPrompt)
    }
    if (initialSearch) {
      setUserSearch(initialSearch)
    }
  }, [initialChannel, initialPrompt, initialSearch])

  // ---- Computed Variables for query ----
  const activePrompt = userPrompt || ''
  const activeSearch = userSearch || false
  const activeChannel = userChannel || null
  const activeCurrentState = currentState || null
  const key = QUERY_KEYS.generateAIPost

  // ---- Hooks ----
  const query = useQuery({
    // Excluding sessionId to avoid re-fetch when it's set after first response
    // eslint-disable-next-line @tanstack/query/exhaustive-deps
    queryKey: [key, activePrompt, activeSearch, activeChannel],
    queryFn: ({ signal }) =>
      generateApi.generatePost(
        {
          user_prompt: activePrompt,
          is_search_enabled: activeSearch,
          ...(activeChannel ? { post_channels: [activeChannel] } : {}),
          ...(sessionId ? { session_id: sessionId } : {}),
          current_state: activeCurrentState,
        },
        signal
      ),
    enabled: !!activePrompt,
    staleTime: 0,
    gcTime: 0,
    refetchOnMount: false,
  })

  // ---- Effects ----
  /**
   * Sets the session id for further API request calls.
   */
  useEffect(() => {
    if (query.data?.data.session_id) {
      setSessionId(query.data.data.session_id)
    }
  }, [query.data?.data.session_id])

  /**
   * Shows the fallback message if it exists
   */
  useEffect(() => {
    if (query.data?.data.fallback_message) {
      toast.info(query.data.data.fallback_message, {
        icon: null,
        duration: 8000,
        closeButton: true,
        className: 'text-xs text-balance',
      })
    }
  }, [query.data?.data.fallback_message])

  /**
   * Ran when genAI API error
   */
  useEffect(() => {
    if (query.error) {
      posthog.captureException(query.error)
      toast.error('Something went wrong, Please try again !')
    }
  }, [query.error])

  // ---- Variables ----
  /**
   * Ref to store previous posts for fallback message case
   */
  const previousPostsRef = useRef<Pick<IPost, 'id' | 'channel' | 'content'>[]>(
    []
  )

  /**
   * Posts generated by the API
   */
  const posts: Pick<IPost, 'id' | 'channel' | 'content'>[] = useMemo(() => {
    const postsResult: Pick<IPost, 'id' | 'channel' | 'content'>[] = []

    // Only update when query is successful and has data
    if (!query.isSuccess || !query.data?.data) {
      return previousPostsRef.current
    }

    // If fallback message is present, return previous state
    if (query.data.data.fallback_message) {
      return previousPostsRef.current
    }

    if (query.data.data.generated_linkedin_post?.content) {
      postsResult.push({
        id: '0',
        channel: 'LinkedIn',
        content: query.data.data.generated_linkedin_post.content,
      })
    }

    if (query.data.data.generated_twitter_post?.content) {
      postsResult.push({
        id: '1',
        channel: 'Twitter',
        content: query.data.data.generated_twitter_post.content,
      })
    }

    // Posthog event
    postHogGenerationCapture(
      postsResult.length,
      query.data.data.original_prompt,
      postsResult.find(p => p.channel === 'LinkedIn')?.content,
      postsResult.find(p => p.channel === 'Twitter')?.content
    )

    // Only update ref if we have new posts
    if (postsResult.length > 0) {
      previousPostsRef.current = postsResult
    }

    return postsResult.length > 0 ? postsResult : previousPostsRef.current
  }, [query.isSuccess, query.data?.data])

  /**
   * TODO: Temporary solution, This should be BE driven
   * Push a history entry whenever the query returns generated posts.
   */
  useEffect(() => {
    const data = query.data?.data

    if (!data) return

    const hasGenerated = Boolean(
      data.generated_linkedin_post?.content ||
        data.generated_twitter_post?.content
    )

    if (!hasGenerated) return

    const entry: HistoryEntry = {
      prompt: data.original_prompt,
      createdAt: new Date().toISOString(),
      posts: [...posts],
    }

    setHistory(prev => [entry, ...prev])
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [query.data?.data])

  /**
   * Extracted links from the API response
   */
  const extractedLinks: SourceChip[] = [
    ...(query.data?.data.external_sources?.map(source => ({
      url: source.url,
      title: source.url,
      description: source.content,
    })) ?? []),
    ...(query.data?.data.search_sources?.map(search => ({
      title: search.query,
      description: search.results,
    })) ?? []),
  ]

  return {
    // Query state
    ...query,

    // Data
    posts,
    extractedLinks,
    history,

    // Current state
    activePrompt,
    key,
    userChannel,
    userPrompt,

    // Setters
    setSessionId,
    setUserPrompt,
    setUserSearch,
    setUserChannel,
  }
}
